trigger:
  branches:
    include:
      - main  # Defina o branch que vai disparar o pipeline

pool:
  vmImage: 'ubuntu-latest'  # Usa a última versão do Ubuntu para rodar o pipeline

steps:
# Primeiro, verifica o código do repositório
- task: Checkout@v2

# Instala o JDK 11 (ou outro JDK dependendo da sua aplicação)
- task: UseJava@1
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'

# Build usando Gradle (substitua 'build' pela task Gradle apropriada, se necessário)
- script: ./gradlew build -x test
  displayName: 'Build Projeto com Gradle'

# Publica o artefato gerado no Azure DevOps para o próximo estágio (artefato é o JAR ou WAR)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/build/libs/*.jar'
    artifactName: 'drop'

# Deploy no Azure App Service usando o artefato publicado
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'effycity-azure'  # Nome da conexão configurada no Azure
    appName: 'Effycity'  # Nome da aplicação no App Service
    package: '$(System.DefaultWorkingDirectory)/drop/*.jar'
